[package]
name = "s-compositor"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
default-run = "s-compositor"

[[bin]]
name = "s-compositor"
path = "src/main.rs"

[dependencies]
s-compositor-wayland.workspace = true
s-compositor-shell.workspace = true
s-compositor-render.workspace = true
s-compositor-tray.workspace = true
slint.workspace = true
glow.workspace = true
chrono.workspace = true
log.workspace = true
env_logger.workspace = true
anyhow.workspace = true
zbus = "5"
async-channel = "2"

[build-dependencies]
slint-build.workspace = true
